[package]
name = "double_linked_list"
version = "0.1.0"
authors = ["Callum Bodels <callum.bodels@bazaarvoice.com>"]
edition = "2018"


[dependencies]
serde = "1.0.118"
serde_json = "1.0.60"


[dev-dependencies]
insta = "1.3.0"
