stages:
  - conventional-commits-linting
  - formatting
  - linting
  - compiling
  - unit-testing


conventional-commits-linting:
  stage: conventional-commits-linting
  image: rust
  before_script:
    - cargo install conventional_commits_linter
  script:
    - COMMON_ANCESTOR_COMMIT=`git merge-base origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME`
    # Lint all the commits in the branch.
    - /usr/local/cargo/bin/conventional_commits_linter --from-commit-hash $COMMON_ANCESTOR_COMMIT --allow-angular-type-only
  rules:
    - if: $CI_MERGE_REQUEST_ID


include:
  - local: .gitlab/ci/binary_search/rust.yml
  - local: .gitlab/ci/quicksort/rust.yml
  - local: .gitlab/ci/selection_sort/rust.yml
